
# Baseline year for DOB checks
TestYear = "2016"

# Validations to invoke
# ValidationRoute = ["schema", "local", "id", "dob", "asl"]
ValidationRoute = ["schema", "id", "dob", "asl"]

# Webserver port
WebServerPort = "1325"

# Performance Parameters
PoolSize = 10
# "MEM | NATS" | "STAN" are alternatives depending on deployment model
MsgTransport = "MEM"      


